spring.application.name=certforge
spring.datasource.url=jdbc:h2:file:./data/certforge;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.messages.basename=messages
certforge.question-bank=classpath:/question-bank/SRE_foundations_140x5.md
